traidex/posts/urls.py
from django.conf.urls import patterns, url

from posts import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^(?P<entry_id>\d+)/$', views.detail, name = 'detail'),
)

traidex/traidex/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'traidex.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^posts/', include('posts.urls', namespace = "posts")),
    url(r'^admin/', include(admin.site.urls)),
)

traidex/posts/models.py
from django.db import models
from localflavor.us.us_states import STATE_CHOICES
from localflavor.us.models import USStateField

class Entry(models.Model):

	#Fixing the plural so it doesn't show up as 'entrys' because that is bothersome
	class Meta:
		verbose_name_plural = 'entries'

	state = USStateField(null = True, blank = True, max_length = 2)
	city = models.CharField(max_length=100)
	text_post = models.CharField(max_length = 2000)
	user = models.CharField(max_length = 50)
	date = models.DateTimeField('publication date')
	title = models.CharField(max_length = 50)

	#constants for trail type choices
	#This seems... roundabout, but whatever.
	GRAVEL = 'Gravel'
	PAVED = 'Paved'
	DIRT = 'Dirt'
	TRAIL_TYPE_CHOICES = (
		(GRAVEL, 'Gravel'),
		(PAVED, 'Paved'),
		(DIRT, 'Dirt'),
	)

	trail_type = models.CharField(max_length = 6, choices = TRAIL_TYPE_CHOICES)

	#More descriptive representation of this object
	def __unicode__(self):
		return 'Trail entry: ' + self.title

class Photo(models.Model):
	photo = models.ImageField(upload_to='photos') #OOER MAN I DUNNO HOW THIS WORKS
	entry = models.ForeignKey(Entry) #This corresponds to one entry.

	#More descriptive representation of this object
	def __unicode__(self):
		return 'Photo for trail entry'

traidex/posts/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext, loader
from django.utils import timezone
from django.core.urlresolvers import reverse

from posts.models import Entry, Photo

def index(request):
	latest_entry_list = Entry.objects.all().order_by('-date')[:5]
	context = {'latest_entry_list' : latest_entry_list}
	return render(request, 'posts/index.html', context)

def detail(request, entry_id):
	entry = get_object_or_404(Entry, pk = entry_id)
	return render(request, 'posts/detail.html', {'entry' : entry})

def create(request):

	if request.method == 'GET':
		return render(request, 'posts/create.html')

	elif request.method == 'POST':
		#Gather POST data from form
		trail_name = request.POST['trail_name']
		post_text = request.POST['text_post']
		
		#Need to validate this and put it behind some kind of flow control
		entry = Entry()
		entry.state = 'SD'
		entry.city = 'Sioux Falls'
		entry.text_post = post_text #This seems unreasonably confusing
		entry.user = 'Armadillus'
		entry.date = timezone.now()
		entry.title = trail_name
		entry.trail_type = 'Paved'
		entry.save()
		return HttpResponseRedirect(reverse('posts:index'))

traidex/posts/templates/posts/create.html
<title>Create a Post</title>
{% if error_message %} <p><strong>{{ error_message}}</strong></p>{% endif %}

<form action="{% url 'posts:create' %}" method="post">
{% csrf_token %} <!--Need this to protect against cross-site request forgery-->
	<input type="text" name="trail_name" id="trail_name" />
	<label for="trail_name">Trail Name: </label><br />
	<input type="text" name="text_post" id="text_post" />
	<label for="text_post">Entry Text: </label><br />
<input type="submit" value="Post" />
</form>

traidex/posts/templates/posts/detail.html
<h1>{{ entry.title }}</h1>
<h2>{{ entry.city }}, {{ entry.state }} <p> Trail Type: {{ entry.trail_type }}</p></h2>
<ul>
	<li>{{ entry.text_post }}</li>
	<li>By: {{ entry.user }}</li>
	<li>Date Posted: {{ entry.date }}</li>
</ul>
<!--Need to get photos to show up here somehow, next.-->

traidex/posts/templates/posts/index.html
<title>Entry List</title>
<a href="{% url 'posts:create' %}">Create a Post</a>

{%  if latest_entry_list %}
	<ul>
	{% for entry in latest_entry_list %}
		<li><a href="{% url 'posts:detail' entry.id %}"> {{ entry.title }}</a></li>
	{% endfor %}
	</ul>
{% else %}
	<p>No entries are available.</p>
{% endif %}